#!/bin/bash
SUBLIME_PATHS=(
    "opt/Sublime Text 2"
    "Library/Application Support/Sublime Text 2"
)

DISCOVER_SUBLIME=""
for SUBLIME in "${SUBLIME_PATHS[@]}"; do
    if [ -d "$REAL_ROOT/$SUBLIME" ]; then
        DISCOVER_SUBLIME=$SUBLIME
        break
    fi
done

if [ -z "$DISCOVER_SUBLIME" ]; then
    echo "discover_sublime: failed to find Sublime Text 2" >&2
    exit 1
fi
