#!/bin/bash
if [[ "$(uname -s)" == "Darwin" ]]; then
    brew install jq
else
    cd files
    autoreconf --install
    ./configure
    make

    mkdir -p "$HM_INSTALL_DIR/bin/"
    cp jq "$HM_INSTALL_DIR/bin/"
fi
