#!/bin/bash
set -euo pipefail

WORKDIR=${WORKDIR:-$(pwd)}
. "$WORKDIR/.tm_sync.config"

: ${REMOTE_USER:=$(whoami)}
: ${REMOTE_PORT:=22}
: ${RSYNC_OPTIONS:=}

RSYNC_CMD="rsync -av --exclude=.tm_sync.config $RSYNC_OPTIONS"
$RSYNC_CMD -e "ssh -p $REMOTE_PORT" \
    "$WORKDIR/" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"

if [[ -n "${REMOTE_POST_COMMAND:-}" ]]; then
    ssh -p "$REMOTE_PORT" "$REMOTE_USER@$REMOTE_HOST" -- "cd \"$REMOTE_PATH\" && $REMOTE_POST_COMMAND 2>&1"
fi
